import "dotenv/config";

import { and, eq } from "drizzle-orm";

import { getDb } from "../src/db";
import {
  categories,
  drafts,
  pipelineJobs,
  reviews,
  routeRules,
  sites,
  storyClusters,
  tenants,
} from "../src/db/schema";

async function main() {
  const db = getDb();

  let tenant = (
    await db.select().from(tenants).where(eq(tenants.slug, "bd-tech-desk"))
  )[0];
  if (!tenant) {
    ;[tenant] = await db
      .insert(tenants)
      .values({
        name: "BD Tech Desk",
        slug: "bd-tech-desk",
        defaultLocale: "en",
      })
      .returning();
  }
  if (!tenant) throw new Error("seed: tenant");

  let site = (
    await db
      .select()
      .from(sites)
      .where(
        and(eq(sites.tenantId, tenant.id), eq(sites.domain, "bdtech.example")),
      )
  )[0];
  if (!site) {
    ;[site] = await db
      .insert(sites)
      .values({
        tenantId: tenant.id,
        domain: "bdtech.example",
        name: "Bangladesh Tech Wire",
        cmsConfig: { type: "headless_stub" },
      })
      .returning();
  }
  if (!site) throw new Error("seed: site");

  async function ensureCategory(
    slug: string,
    nameEn: string,
    nameBn: string,
  ) {
    const existing = (
      await db
        .select()
        .from(categories)
        .where(
          and(eq(categories.siteId, site!.id), eq(categories.slug, slug)),
        )
    )[0];
    if (existing) return existing;
    const [row] = await db
      .insert(categories)
      .values({ siteId: site!.id, slug, nameEn, nameBn })
      .returning();
    if (!row) throw new Error(`seed: category ${slug}`);
    return row;
  }

  const catAi = await ensureCategory(
    "artificial-intelligence",
    "Artificial intelligence",
    "কৃত্রিম বুদ্ধিমত্তা",
  );
  const catStartup = await ensureCategory(
    "startups-dhaka",
    "Startups · Dhaka",
    "স্টার্টআপ · ঢাকা",
  );
  const catPolicy = await ensureCategory(
    "digital-policy",
    "Digital policy",
    "ডিজিটাল নীতি",
  );

  const existingRules = await db
    .select({ id: routeRules.id })
    .from(routeRules)
    .where(eq(routeRules.tenantId, tenant.id));
  if (existingRules.length === 0) {
    await db.insert(routeRules).values([
      {
        tenantId: tenant.id,
        priority: 10,
        matchJson: { topicIncludes: ["ai"], locale: "en" },
        targetSiteId: site.id,
        targetCategoryId: catAi.id,
      },
      {
        tenantId: tenant.id,
        priority: 20,
        matchJson: { topicIncludes: ["startup"], locale: "bn" },
        targetSiteId: site.id,
        targetCategoryId: catStartup.id,
      },
      {
        tenantId: tenant.id,
        priority: 30,
        matchJson: { topicIncludes: ["policy"], locale: "en" },
        targetSiteId: site.id,
        targetCategoryId: catPolicy.id,
      },
    ]);
  }

  let cluster = (
    await db
      .select()
      .from(storyClusters)
      .where(
        and(
          eq(storyClusters.tenantId, tenant.id),
          eq(
            storyClusters.fingerprint,
            "demo-cluster-national-ai-compute-2026",
          ),
        ),
      )
  )[0];
  if (!cluster) {
    ;[cluster] = await db
      .insert(storyClusters)
      .values({
        tenantId: tenant.id,
        fingerprint: "demo-cluster-national-ai-compute-2026",
        topicTags: ["ai", "policy", "bangladesh"],
        summaryHint: "National AI compute and startup ecosystem updates",
      })
      .returning();
  }
  if (!cluster) throw new Error("seed: cluster");

  const existingDrafts = await db
    .select({ id: drafts.id })
    .from(drafts)
    .where(eq(drafts.storyClusterId, cluster.id));

  if (existingDrafts.length === 0) {
    const created = await db
      .insert(drafts)
      .values([
        {
          tenantId: tenant.id,
          storyClusterId: cluster.id,
          locale: "en",
          status: "in_review",
          title: "Bangladesh lines up GPU access for AI startups",
          dek: "Policy signals and compute strategy are converging—editors should verify against primary sources.",
          bodyMd: `## Outline\n\n- Draft generated by **stub pipeline** (replace with real agents).\n- Check claims about funding amounts and timelines against official releases.\n\n## Suggested angle\n\nConnect **startup demand** in Dhaka/Chattogram with **sovereign compute** narratives in the national AI policy conversation.\n`,
          provenanceJson: {
            sources: ["internal:demo-seed"],
            model: "none",
          },
          riskScore: 2,
        },
        {
          tenantId: tenant.id,
          storyClusterId: cluster.id,
          locale: "bn",
          status: "in_review",
          title: "এআই স্টার্টআপদের জন্য জিপিউ সুবিধা: নীতি ও বাস্তবতা",
          dek: "সরকারি ঘোষণা ও বাজেটের সংখ্যা অবশ্যই মূল নথি থেকে নিশ্চিত করুন।",
          bodyMd: `## খসড়া\n\n- এটি **ডেমো সিড** — পরে মাল্টি-এজেন্ট লেখা বসাবেন।\n- অর্থের পরিমাণ ও সময়সীমা **প্রাথমিক উৎস** ছাড়া প্রকাশ করবেন না।\n`,
          provenanceJson: {
            sources: ["internal:demo-seed"],
            model: "none",
          },
          riskScore: 2,
        },
      ])
      .returning({ id: drafts.id });

    for (const d of created) {
      await db.insert(reviews).values({ draftId: d.id, decision: "pending" });
    }
  }

  await db.insert(pipelineJobs).values({
    type: "synthesize.stub",
    payload: {
      tenantId: tenant.id,
      storyClusterId: cluster.id,
      note: "enqueue example job for worker",
    },
  });

  console.log("Seed complete for tenant", tenant.slug);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
